name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "bb2d8f96-2436-4e65-a29b-827d6891d36e"      # 替换为你创建的数据库 ID
