name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow-db-db"  # 替换为你创建的数据库名称
database_id = "9c5fac4f-6880-4194-9b2b-ae958ad61020"      # 替换为你创建的数据库 ID
