name = "newsnow"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnowdb"  # 替换为你创建的数据库名称
database_id = "3d597238-f802-43e0-821f-56ca95959711"      # 替换为你创建的数据库 ID
